postgres:
  user: ${PHC_DB_USER}
  password: ${PHC_DB_PASSWORD}
  host: ${PHC_DB_HOST}
  port: ${PHC_DB_PORT}
  database: ${PHC_DB_NAME}

jaeger:
  host: ${PHC_JAEGER_HOST}
  port: ${PHC_JAEGER_PORT}
  service_name: ${PHC_JAEGER_NAME}